/* tslint:disable */
/* eslint-disable */
/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {ApiAreaTree, ApiAreaTrees, ApiAreaTreeSingle} from '../model';

/**
 * AreaTreeApi - axios parameter creator
 * @export
 */
export const AreaTreeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Returns areaTrees inventories by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAreaTrees: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/areaTrees`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single areaTree
         * @summary Find AreaTree by ID
         * @param {number} areaId ID of areaTree to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAreaTreeById: async (areaId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'areaId' is not null or undefined
            assertParamExists('getAreaTreeById', 'areaId', areaId)
            const localVarPath = `/areaTrees/{areaId}`
                .replace(`{${"areaId"}}`, encodeURIComponent(String(areaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update an existing AreaTree
         * @param {number} areaId ID of areaTree to return
         * @param {ApiAreaTree} apiAreaTree AreaTree object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAreaTree: async (areaId: number, apiAreaTree: ApiAreaTree, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'areaId' is not null or undefined
            assertParamExists('updateAreaTree', 'areaId', areaId)
            // verify required parameter 'apiAreaTree' is not null or undefined
            assertParamExists('updateAreaTree', 'apiAreaTree', apiAreaTree)
            const localVarPath = `/areaTrees/{areaId}`
                .replace(`{${"areaId"}}`, encodeURIComponent(String(areaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiAreaTree, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AreaTreeApi - functional programming interface
 * @export
 */
export const AreaTreeApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = AreaTreeApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Returns areaTrees inventories by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAreaTrees(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaTrees>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAreaTrees(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a single areaTree
         * @summary Find AreaTree by ID
         * @param {number} areaId ID of areaTree to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAreaTreeById(areaId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaTreeSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAreaTreeById(areaId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update an existing AreaTree
         * @param {number} areaId ID of areaTree to return
         * @param {ApiAreaTree} apiAreaTree AreaTree object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAreaTree(areaId: number, apiAreaTree: ApiAreaTree, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaTreeSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAreaTree(areaId, apiAreaTree, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AreaTreeApi - factory interface
 * @export
 */
export const AreaTreeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AreaTreeApiFp(configuration)
    return {
        /**
         *
         * @summary Returns areaTrees inventories by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAreaTrees(options?: any): AxiosPromise<ApiAreaTrees> {
            return localVarFp.getAllAreaTrees(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single areaTree
         * @summary Find AreaTree by ID
         * @param {number} areaId ID of areaTree to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAreaTreeById(areaId: number, options?: any): AxiosPromise<ApiAreaTreeSingle> {
            return localVarFp.getAreaTreeById(areaId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update an existing AreaTree
         * @param {number} areaId ID of areaTree to return
         * @param {ApiAreaTree} apiAreaTree AreaTree object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAreaTree(areaId: number, apiAreaTree: ApiAreaTree, options?: any): AxiosPromise<ApiAreaTreeSingle> {
            return localVarFp.updateAreaTree(areaId, apiAreaTree, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AreaTreeApi - object-oriented interface
 * @export
 * @class AreaTreeApi
 * @extends {BaseAPI}
 */
export class AreaTreeApi extends BaseAPI {
    /**
     *
     * @summary Returns areaTrees inventories by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaTreeApi
     */
    public getAllAreaTrees(options?: any) {
        return AreaTreeApiFp(this.configuration).getAllAreaTrees(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single areaTree
     * @summary Find AreaTree by ID
     * @param {number} areaId ID of areaTree to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaTreeApi
     */
    public getAreaTreeById(areaId: number, options?: any) {
        return AreaTreeApiFp(this.configuration).getAreaTreeById(areaId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update an existing AreaTree
     * @param {number} areaId ID of areaTree to return
     * @param {ApiAreaTree} apiAreaTree AreaTree object that needs to be added to the store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaTreeApi
     */
    public updateAreaTree(areaId: number, apiAreaTree: ApiAreaTree, options?: any) {
        return AreaTreeApiFp(this.configuration).updateAreaTree(areaId, apiAreaTree, options).then((request) => request(this.axios, this.basePath));
    }
}
