/* tslint:disable */
/* eslint-disable */
/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {ApiArea, ApiAreas, ApiAreaSingle, ApiAreaToAdd} from '../model';

/**
 * AreaApi - axios parameter creator
 * @export
 */
export const AreaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Add a new Area
         * @param {ApiAreaToAdd} apiAreaToAdd Area object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addArea: async (apiAreaToAdd: ApiAreaToAdd, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiAreaToAdd' is not null or undefined
            assertParamExists('addArea', 'apiAreaToAdd', apiAreaToAdd)
            const localVarPath = `/areas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiAreaToAdd, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deletes a area
         * @param {number} areaId Area id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArea: async (areaId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'areaId' is not null or undefined
            assertParamExists('deleteArea', 'areaId', areaId)
            const localVarPath = `/areas/{areaId}`
                .replace(`{${"areaId"}}`, encodeURIComponent(String(areaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Returns areas inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAreas: async (sort?: string, order?: string, start?: number, end?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/areas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }

            if (start !== undefined) {
                localVarQueryParameter['_start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['_end'] = end;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single area
         * @summary Find Area by ID
         * @param {number} areaId ID of area to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAreaById: async (areaId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'areaId' is not null or undefined
            assertParamExists('getAreaById', 'areaId', areaId)
            const localVarPath = `/areas/{areaId}`
                .replace(`{${"areaId"}}`, encodeURIComponent(String(areaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update an existing Area
         * @param {number} areaId ID of area to return
         * @param {ApiArea} apiArea Area object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateArea: async (areaId: number, apiArea: ApiArea, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'areaId' is not null or undefined
            assertParamExists('updateArea', 'areaId', areaId)
            // verify required parameter 'apiArea' is not null or undefined
            assertParamExists('updateArea', 'apiArea', apiArea)
            const localVarPath = `/areas/{areaId}`
                .replace(`{${"areaId"}}`, encodeURIComponent(String(areaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiArea, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AreaApi - functional programming interface
 * @export
 */
export const AreaApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = AreaApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Add a new Area
         * @param {ApiAreaToAdd} apiAreaToAdd Area object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addArea(apiAreaToAdd: ApiAreaToAdd, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addArea(apiAreaToAdd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Deletes a area
         * @param {number} areaId Area id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteArea(areaId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteArea(areaId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Returns areas inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAreas(sort?: string, order?: string, start?: number, end?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreas>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAreas(sort, order, start, end, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a single area
         * @summary Find Area by ID
         * @param {number} areaId ID of area to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAreaById(areaId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAreaById(areaId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update an existing Area
         * @param {number} areaId ID of area to return
         * @param {ApiArea} apiArea Area object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateArea(areaId: number, apiArea: ApiArea, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAreaSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateArea(areaId, apiArea, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AreaApi - factory interface
 * @export
 */
export const AreaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AreaApiFp(configuration)
    return {
        /**
         *
         * @summary Add a new Area
         * @param {ApiAreaToAdd} apiAreaToAdd Area object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addArea(apiAreaToAdd: ApiAreaToAdd, options?: any): AxiosPromise<ApiAreaSingle> {
            return localVarFp.addArea(apiAreaToAdd, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deletes a area
         * @param {number} areaId Area id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArea(areaId: number, options?: any): AxiosPromise<ApiAreaSingle> {
            return localVarFp.deleteArea(areaId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Returns areas inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAreas(sort?: string, order?: string, start?: number, end?: number, options?: any): AxiosPromise<ApiAreas> {
            return localVarFp.getAllAreas(sort, order, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single area
         * @summary Find Area by ID
         * @param {number} areaId ID of area to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAreaById(areaId: number, options?: any): AxiosPromise<ApiAreaSingle> {
            return localVarFp.getAreaById(areaId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update an existing Area
         * @param {number} areaId ID of area to return
         * @param {ApiArea} apiArea Area object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateArea(areaId: number, apiArea: ApiArea, options?: any): AxiosPromise<ApiAreaSingle> {
            return localVarFp.updateArea(areaId, apiArea, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AreaApi - object-oriented interface
 * @export
 * @class AreaApi
 * @extends {BaseAPI}
 */
export class AreaApi extends BaseAPI {
    /**
     *
     * @summary Add a new Area
     * @param {ApiAreaToAdd} apiAreaToAdd Area object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaApi
     */
    public addArea(apiAreaToAdd: ApiAreaToAdd, options?: any) {
        return AreaApiFp(this.configuration).addArea(apiAreaToAdd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deletes a area
     * @param {number} areaId Area id to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaApi
     */
    public deleteArea(areaId: number, options?: any) {
        return AreaApiFp(this.configuration).deleteArea(areaId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Returns areas inventories by status
     * @param {string} [sort] sorting column
     * @param {string} [order] ASC / DESC
     * @param {number} [start] Start position of retrieved data
     * @param {number} [end] End position of retrieved data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaApi
     */
    public getAllAreas(sort?: string, order?: string, start?: number, end?: number, options?: any) {
        return AreaApiFp(this.configuration).getAllAreas(sort, order, start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single area
     * @summary Find Area by ID
     * @param {number} areaId ID of area to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaApi
     */
    public getAreaById(areaId: number, options?: any) {
        return AreaApiFp(this.configuration).getAreaById(areaId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update an existing Area
     * @param {number} areaId ID of area to return
     * @param {ApiArea} apiArea Area object that needs to be added to the store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AreaApi
     */
    public updateArea(areaId: number, apiArea: ApiArea, options?: any) {
        return AreaApiFp(this.configuration).updateArea(areaId, apiArea, options).then((request) => request(this.axios, this.basePath));
    }
}
