/* tslint:disable */
/* eslint-disable */
/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {
    ApiContractorProjectChangePrice,
    ApiContractorProjectComplete,
    ApiContractorProjectProposal,
    ApiContractorProjects,
    ApiContractorProjectShow
} from '../model';

/**
 * ContractorProjectsApi - axios parameter creator
 * @export
 */
export const ContractorProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Update an existing contractorProjectApplication
         * @param {ApiContractorProjectChangePrice} apiContractorProjectChangePrice change the price of projectApplication from orderer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePriceContractorProjectApplication: async (apiContractorProjectChangePrice: ApiContractorProjectChangePrice, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiContractorProjectChangePrice' is not null or undefined
            assertParamExists('changePriceContractorProjectApplication', 'apiContractorProjectChangePrice', apiContractorProjectChangePrice)
            const localVarPath = `/mypage/contractorProjects/changePrice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiContractorProjectChangePrice, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary complete a projectApplication
         * @param {ApiContractorProjectComplete} apiContractorProjectComplete contractor project that needs to be completed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeProjectApplication: async (apiContractorProjectComplete: ApiContractorProjectComplete, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiContractorProjectComplete' is not null or undefined
            assertParamExists('completeProjectApplication', 'apiContractorProjectComplete', apiContractorProjectComplete)
            const localVarPath = `/mypage/contractorProjects/complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiContractorProjectComplete, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Returns contractorProjects
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllContractorProjects: async (sort?: string, order?: string, start?: number, end?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/mypage/contractorProjects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }

            if (start !== undefined) {
                localVarQueryParameter['_start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['_end'] = end;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Find contractorProjects by ID
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContractorProjectById: async (projectApplicationId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectApplicationId' is not null or undefined
            assertParamExists('getContractorProjectById', 'projectApplicationId', projectApplicationId)
            const localVarPath = `/mypage/contractorProjects/show/{projectApplicationId}`
                .replace(`{${"projectApplicationId"}}`, encodeURIComponent(String(projectApplicationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Proposal contractorProjectApplication
         * @param {ApiContractorProjectProposal} apiContractorProjectProposal change the price of projectApplication from orderer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proposalContractorProjectApplication: async (apiContractorProjectProposal: ApiContractorProjectProposal, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiContractorProjectProposal' is not null or undefined
            assertParamExists('proposalContractorProjectApplication', 'apiContractorProjectProposal', apiContractorProjectProposal)
            const localVarPath = `/mypage/contractorProjects/proposal`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiContractorProjectProposal, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContractorProjectsApi - functional programming interface
 * @export
 */
export const ContractorProjectsApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = ContractorProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Update an existing contractorProjectApplication
         * @param {ApiContractorProjectChangePrice} apiContractorProjectChangePrice change the price of projectApplication from orderer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePriceContractorProjectApplication(apiContractorProjectChangePrice: ApiContractorProjectChangePrice, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiContractorProjectShow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePriceContractorProjectApplication(apiContractorProjectChangePrice, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary complete a projectApplication
         * @param {ApiContractorProjectComplete} apiContractorProjectComplete contractor project that needs to be completed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completeProjectApplication(apiContractorProjectComplete: ApiContractorProjectComplete, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiContractorProjectShow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.completeProjectApplication(apiContractorProjectComplete, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Returns contractorProjects
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllContractorProjects(sort?: string, order?: string, start?: number, end?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiContractorProjects>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllContractorProjects(sort, order, start, end, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Find contractorProjects by ID
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContractorProjectById(projectApplicationId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiContractorProjectShow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContractorProjectById(projectApplicationId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Proposal contractorProjectApplication
         * @param {ApiContractorProjectProposal} apiContractorProjectProposal change the price of projectApplication from orderer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async proposalContractorProjectApplication(apiContractorProjectProposal: ApiContractorProjectProposal, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiContractorProjectShow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.proposalContractorProjectApplication(apiContractorProjectProposal, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ContractorProjectsApi - factory interface
 * @export
 */
export const ContractorProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContractorProjectsApiFp(configuration)
    return {
        /**
         *
         * @summary Update an existing contractorProjectApplication
         * @param {ApiContractorProjectChangePrice} apiContractorProjectChangePrice change the price of projectApplication from orderer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePriceContractorProjectApplication(apiContractorProjectChangePrice: ApiContractorProjectChangePrice, options?: any): AxiosPromise<ApiContractorProjectShow> {
            return localVarFp.changePriceContractorProjectApplication(apiContractorProjectChangePrice, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary complete a projectApplication
         * @param {ApiContractorProjectComplete} apiContractorProjectComplete contractor project that needs to be completed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeProjectApplication(apiContractorProjectComplete: ApiContractorProjectComplete, options?: any): AxiosPromise<ApiContractorProjectShow> {
            return localVarFp.completeProjectApplication(apiContractorProjectComplete, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Returns contractorProjects
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllContractorProjects(sort?: string, order?: string, start?: number, end?: number, options?: any): AxiosPromise<ApiContractorProjects> {
            return localVarFp.getAllContractorProjects(sort, order, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Find contractorProjects by ID
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContractorProjectById(projectApplicationId: number, options?: any): AxiosPromise<ApiContractorProjectShow> {
            return localVarFp.getContractorProjectById(projectApplicationId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Proposal contractorProjectApplication
         * @param {ApiContractorProjectProposal} apiContractorProjectProposal change the price of projectApplication from orderer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proposalContractorProjectApplication(apiContractorProjectProposal: ApiContractorProjectProposal, options?: any): AxiosPromise<ApiContractorProjectShow> {
            return localVarFp.proposalContractorProjectApplication(apiContractorProjectProposal, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContractorProjectsApi - object-oriented interface
 * @export
 * @class ContractorProjectsApi
 * @extends {BaseAPI}
 */
export class ContractorProjectsApi extends BaseAPI {
    /**
     *
     * @summary Update an existing contractorProjectApplication
     * @param {ApiContractorProjectChangePrice} apiContractorProjectChangePrice change the price of projectApplication from orderer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractorProjectsApi
     */
    public changePriceContractorProjectApplication(apiContractorProjectChangePrice: ApiContractorProjectChangePrice, options?: any) {
        return ContractorProjectsApiFp(this.configuration).changePriceContractorProjectApplication(apiContractorProjectChangePrice, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary complete a projectApplication
     * @param {ApiContractorProjectComplete} apiContractorProjectComplete contractor project that needs to be completed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractorProjectsApi
     */
    public completeProjectApplication(apiContractorProjectComplete: ApiContractorProjectComplete, options?: any) {
        return ContractorProjectsApiFp(this.configuration).completeProjectApplication(apiContractorProjectComplete, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Returns contractorProjects
     * @param {string} [sort] sorting column
     * @param {string} [order] ASC / DESC
     * @param {number} [start] Start position of retrieved data
     * @param {number} [end] End position of retrieved data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractorProjectsApi
     */
    public getAllContractorProjects(sort?: string, order?: string, start?: number, end?: number, options?: any) {
        return ContractorProjectsApiFp(this.configuration).getAllContractorProjects(sort, order, start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Find contractorProjects by ID
     * @param {number} projectApplicationId ID of projectApplication to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractorProjectsApi
     */
    public getContractorProjectById(projectApplicationId: number, options?: any) {
        return ContractorProjectsApiFp(this.configuration).getContractorProjectById(projectApplicationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Proposal contractorProjectApplication
     * @param {ApiContractorProjectProposal} apiContractorProjectProposal change the price of projectApplication from orderer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractorProjectsApi
     */
    public proposalContractorProjectApplication(apiContractorProjectProposal: ApiContractorProjectProposal, options?: any) {
        return ContractorProjectsApiFp(this.configuration).proposalContractorProjectApplication(apiContractorProjectProposal, options).then((request) => request(this.axios, this.basePath));
    }
}
