/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {ApiGenre, ApiGenres, ApiGenreSingle, ApiGenreToAdd} from '../model';

/**
 * GenreApi - axios parameter creator
 * @export
 */
export const GenreApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Add a new Genre
         * @param {ApiGenreToAdd} apiGenreToAdd Genre object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addGenre: async (apiGenreToAdd: ApiGenreToAdd, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiGenreToAdd' is not null or undefined
            assertParamExists('addGenre', 'apiGenreToAdd', apiGenreToAdd)
            const localVarPath = `/genres`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiGenreToAdd, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deletes a genre
         * @param {number} genreId Genre id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGenre: async (genreId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genreId' is not null or undefined
            assertParamExists('deleteGenre', 'genreId', genreId)
            const localVarPath = `/genres/{genreId}`
                .replace(`{${"genreId"}}`, encodeURIComponent(String(genreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Returns genres inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllGenres: async (sort?: string, order?: string, start?: number, end?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/genres`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }

            if (start !== undefined) {
                localVarQueryParameter['_start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['_end'] = end;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single genre
         * @summary Find Genre by ID
         * @param {number} genreId ID of genre to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGenreById: async (genreId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genreId' is not null or undefined
            assertParamExists('getGenreById', 'genreId', genreId)
            const localVarPath = `/genres/{genreId}`
                .replace(`{${"genreId"}}`, encodeURIComponent(String(genreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update an existing Genre
         * @param {number} genreId ID of genre to return
         * @param {ApiGenre} apiGenre Genre object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGenre: async (genreId: number, apiGenre: ApiGenre, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genreId' is not null or undefined
            assertParamExists('updateGenre', 'genreId', genreId)
            // verify required parameter 'apiGenre' is not null or undefined
            assertParamExists('updateGenre', 'apiGenre', apiGenre)
            const localVarPath = `/genres/{genreId}`
                .replace(`{${"genreId"}}`, encodeURIComponent(String(genreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiGenre, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GenreApi - functional programming interface
 * @export
 */
export const GenreApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = GenreApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Add a new Genre
         * @param {ApiGenreToAdd} apiGenreToAdd Genre object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addGenre(apiGenreToAdd: ApiGenreToAdd, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGenreSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addGenre(apiGenreToAdd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Deletes a genre
         * @param {number} genreId Genre id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGenre(genreId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGenreSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteGenre(genreId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Returns genres inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllGenres(sort?: string, order?: string, start?: number, end?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGenres>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllGenres(sort, order, start, end, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a single genre
         * @summary Find Genre by ID
         * @param {number} genreId ID of genre to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGenreById(genreId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGenreSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGenreById(genreId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update an existing Genre
         * @param {number} genreId ID of genre to return
         * @param {ApiGenre} apiGenre Genre object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateGenre(genreId: number, apiGenre: ApiGenre, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGenreSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateGenre(genreId, apiGenre, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GenreApi - factory interface
 * @export
 */
export const GenreApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GenreApiFp(configuration)
    return {
        /**
         *
         * @summary Add a new Genre
         * @param {ApiGenreToAdd} apiGenreToAdd Genre object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addGenre(apiGenreToAdd: ApiGenreToAdd, options?: any): AxiosPromise<ApiGenreSingle> {
            return localVarFp.addGenre(apiGenreToAdd, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deletes a genre
         * @param {number} genreId Genre id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGenre(genreId: number, options?: any): AxiosPromise<ApiGenreSingle> {
            return localVarFp.deleteGenre(genreId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Returns genres inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllGenres(sort?: string, order?: string, start?: number, end?: number, options?: any): AxiosPromise<ApiGenres> {
            return localVarFp.getAllGenres(sort, order, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single genre
         * @summary Find Genre by ID
         * @param {number} genreId ID of genre to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGenreById(genreId: number, options?: any): AxiosPromise<ApiGenreSingle> {
            return localVarFp.getGenreById(genreId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update an existing Genre
         * @param {number} genreId ID of genre to return
         * @param {ApiGenre} apiGenre Genre object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGenre(genreId: number, apiGenre: ApiGenre, options?: any): AxiosPromise<ApiGenreSingle> {
            return localVarFp.updateGenre(genreId, apiGenre, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GenreApi - object-oriented interface
 * @export
 * @class GenreApi
 * @extends {BaseAPI}
 */
export class GenreApi extends BaseAPI {
    /**
     *
     * @summary Add a new Genre
     * @param {ApiGenreToAdd} apiGenreToAdd Genre object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenreApi
     */
    public addGenre(apiGenreToAdd: ApiGenreToAdd, options?: any) {
        return GenreApiFp(this.configuration).addGenre(apiGenreToAdd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deletes a genre
     * @param {number} genreId Genre id to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenreApi
     */
    public deleteGenre(genreId: number, options?: any) {
        return GenreApiFp(this.configuration).deleteGenre(genreId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Returns genres inventories by status
     * @param {string} [sort] sorting column
     * @param {string} [order] ASC / DESC
     * @param {number} [start] Start position of retrieved data
     * @param {number} [end] End position of retrieved data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenreApi
     */
    public getAllGenres(sort?: string, order?: string, start?: number, end?: number, options?: any) {
        return GenreApiFp(this.configuration).getAllGenres(sort, order, start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single genre
     * @summary Find Genre by ID
     * @param {number} genreId ID of genre to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenreApi
     */
    public getGenreById(genreId: number, options?: any) {
        return GenreApiFp(this.configuration).getGenreById(genreId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update an existing Genre
     * @param {number} genreId ID of genre to return
     * @param {ApiGenre} apiGenre Genre object that needs to be added to the store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenreApi
     */
    public updateGenre(genreId: number, apiGenre: ApiGenre, options?: any) {
        return GenreApiFp(this.configuration).updateGenre(genreId, apiGenre, options).then((request) => request(this.axios, this.basePath));
    }
}
