/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {
    ApiProjectsSearch,
    ApiProjectToSearch,
    ApiUserFavoriteProjectSingle,
    ApiUserFavoriteProjectToAdd
} from '../model';
import CONFIG from "../../const/DaoConfig";

/**
 * MypageFavoritesApi - axios parameter creator
 * @export
 */
export const MypageFavoritesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Add a new UserFavoriteProject
         * @param {ApiUserFavoriteProjectToAdd} apiUserFavoriteProjectToAdd UserFavoriteProject object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMypageFavorite: async (apiUserFavoriteProjectToAdd: ApiUserFavoriteProjectToAdd, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiUserFavoriteProjectToAdd' is not null or undefined
            assertParamExists('addMypageFavorite', 'apiUserFavoriteProjectToAdd', apiUserFavoriteProjectToAdd)
            const localVarPath = `/mypage/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'POST', ...baseOptions, ...options};
            let localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter = CONFIG().CONFIG_HEADER().headers

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiUserFavoriteProjectToAdd, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deletes a mypage favorite
         * @param {ApiUserFavoriteProjectToAdd} [apiUserFavoriteProjectToAdd]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMypageFavorite: async (apiUserFavoriteProjectToAdd?: ApiUserFavoriteProjectToAdd, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/mypage/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'DELETE', ...baseOptions, ...options};
            let localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter = CONFIG().CONFIG_HEADER().headers

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiUserFavoriteProjectToAdd, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Returns mypageFavorites
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {ApiProjectToSearch} [apiProjectToSearch]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMypageFavorites: async (sort?: string, order?: string, start?: number, end?: number, apiProjectToSearch?: ApiProjectToSearch, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/mypage/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            let localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }

            if (start !== undefined) {
                localVarQueryParameter['_start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['_end'] = end;
            }


            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter = CONFIG().CONFIG_HEADER().headers

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiProjectToSearch, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MypageFavoritesApi - functional programming interface
 * @export
 */
export const MypageFavoritesApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = MypageFavoritesApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Add a new UserFavoriteProject
         * @param {ApiUserFavoriteProjectToAdd} apiUserFavoriteProjectToAdd UserFavoriteProject object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addMypageFavorite(apiUserFavoriteProjectToAdd: ApiUserFavoriteProjectToAdd, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserFavoriteProjectSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addMypageFavorite(apiUserFavoriteProjectToAdd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Deletes a mypage favorite
         * @param {ApiUserFavoriteProjectToAdd} [apiUserFavoriteProjectToAdd]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMypageFavorite(apiUserFavoriteProjectToAdd?: ApiUserFavoriteProjectToAdd, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserFavoriteProjectSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMypageFavorite(apiUserFavoriteProjectToAdd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Returns mypageFavorites
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {ApiProjectToSearch} [apiProjectToSearch]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMypageFavorites(sort?: string, order?: string, start?: number, end?: number, apiProjectToSearch?: ApiProjectToSearch, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiProjectsSearch>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMypageFavorites(sort, order, start, end, apiProjectToSearch, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MypageFavoritesApi - factory interface
 * @export
 */
export const MypageFavoritesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MypageFavoritesApiFp(configuration)
    return {
        /**
         *
         * @summary Add a new UserFavoriteProject
         * @param {ApiUserFavoriteProjectToAdd} apiUserFavoriteProjectToAdd UserFavoriteProject object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMypageFavorite(apiUserFavoriteProjectToAdd: ApiUserFavoriteProjectToAdd, options?: any): AxiosPromise<ApiUserFavoriteProjectSingle> {
            return localVarFp.addMypageFavorite(apiUserFavoriteProjectToAdd, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deletes a mypage favorite
         * @param {ApiUserFavoriteProjectToAdd} [apiUserFavoriteProjectToAdd]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMypageFavorite(apiUserFavoriteProjectToAdd?: ApiUserFavoriteProjectToAdd, options?: any): AxiosPromise<ApiUserFavoriteProjectSingle> {
            return localVarFp.deleteMypageFavorite(apiUserFavoriteProjectToAdd, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Returns mypageFavorites
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {ApiProjectToSearch} [apiProjectToSearch]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMypageFavorites(sort?: string, order?: string, start?: number, end?: number, apiProjectToSearch?: ApiProjectToSearch, options?: any): AxiosPromise<ApiProjectsSearch> {
            return localVarFp.getAllMypageFavorites(sort, order, start, end, apiProjectToSearch, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MypageFavoritesApi - object-oriented interface
 * @export
 * @class MypageFavoritesApi
 * @extends {BaseAPI}
 */
export class MypageFavoritesApi extends BaseAPI {
    /**
     *
     * @summary Add a new UserFavoriteProject
     * @param {ApiUserFavoriteProjectToAdd} apiUserFavoriteProjectToAdd UserFavoriteProject object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MypageFavoritesApi
     */
    public addMypageFavorite(apiUserFavoriteProjectToAdd: ApiUserFavoriteProjectToAdd, options?: any) {
        return MypageFavoritesApiFp(this.configuration).addMypageFavorite(apiUserFavoriteProjectToAdd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deletes a mypage favorite
     * @param {ApiUserFavoriteProjectToAdd} [apiUserFavoriteProjectToAdd]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MypageFavoritesApi
     */
    public deleteMypageFavorite(apiUserFavoriteProjectToAdd?: ApiUserFavoriteProjectToAdd, options?: any) {
        return MypageFavoritesApiFp(this.configuration).deleteMypageFavorite(apiUserFavoriteProjectToAdd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Returns mypageFavorites
     * @param {string} [sort] sorting column
     * @param {string} [order] ASC / DESC
     * @param {number} [start] Start position of retrieved data
     * @param {number} [end] End position of retrieved data
     * @param {ApiProjectToSearch} [apiProjectToSearch]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MypageFavoritesApi
     */
    public getAllMypageFavorites(sort?: string, order?: string, start?: number, end?: number, apiProjectToSearch?: ApiProjectToSearch, options?: any) {
        return MypageFavoritesApiFp(this.configuration).getAllMypageFavorites(sort, order, start, end, apiProjectToSearch, options).then((request) => request(this.axios, this.basePath));
    }
}
