/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {ApiNgWord, ApiNgWords, ApiNgWordSingle, ApiNgWordToAdd} from '../model';

/**
 * NgWordApi - axios parameter creator
 * @export
 */
export const NgWordApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Add a new NgWord
         * @param {ApiNgWordToAdd} apiNgWordToAdd NgWord object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNgWord: async (apiNgWordToAdd: ApiNgWordToAdd, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiNgWordToAdd' is not null or undefined
            assertParamExists('addNgWord', 'apiNgWordToAdd', apiNgWordToAdd)
            const localVarPath = `/ngWords`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiNgWordToAdd, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deletes a ngWord
         * @param {number} ngWordId NgWord id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNgWord: async (ngWordId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ngWordId' is not null or undefined
            assertParamExists('deleteNgWord', 'ngWordId', ngWordId)
            const localVarPath = `/ngWords/{ngWordId}`
                .replace(`{${"ngWordId"}}`, encodeURIComponent(String(ngWordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Returns ngWords inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNgWords: async (sort?: string, order?: string, start?: number, end?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/ngWords`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }

            if (start !== undefined) {
                localVarQueryParameter['_start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['_end'] = end;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single ngWord
         * @summary Find NgWord by ID
         * @param {number} ngWordId ID of ngWord to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNgWordById: async (ngWordId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ngWordId' is not null or undefined
            assertParamExists('getNgWordById', 'ngWordId', ngWordId)
            const localVarPath = `/ngWords/{ngWordId}`
                .replace(`{${"ngWordId"}}`, encodeURIComponent(String(ngWordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update an existing NgWord
         * @param {number} ngWordId ID of ngWord to return
         * @param {ApiNgWord} apiNgWord NgWord object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNgWord: async (ngWordId: number, apiNgWord: ApiNgWord, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ngWordId' is not null or undefined
            assertParamExists('updateNgWord', 'ngWordId', ngWordId)
            // verify required parameter 'apiNgWord' is not null or undefined
            assertParamExists('updateNgWord', 'apiNgWord', apiNgWord)
            const localVarPath = `/ngWords/{ngWordId}`
                .replace(`{${"ngWordId"}}`, encodeURIComponent(String(ngWordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiNgWord, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NgWordApi - functional programming interface
 * @export
 */
export const NgWordApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = NgWordApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Add a new NgWord
         * @param {ApiNgWordToAdd} apiNgWordToAdd NgWord object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNgWord(apiNgWordToAdd: ApiNgWordToAdd, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiNgWordSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNgWord(apiNgWordToAdd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Deletes a ngWord
         * @param {number} ngWordId NgWord id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteNgWord(ngWordId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiNgWordSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteNgWord(ngWordId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Returns ngWords inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllNgWords(sort?: string, order?: string, start?: number, end?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiNgWords>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllNgWords(sort, order, start, end, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a single ngWord
         * @summary Find NgWord by ID
         * @param {number} ngWordId ID of ngWord to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNgWordById(ngWordId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiNgWordSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNgWordById(ngWordId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update an existing NgWord
         * @param {number} ngWordId ID of ngWord to return
         * @param {ApiNgWord} apiNgWord NgWord object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateNgWord(ngWordId: number, apiNgWord: ApiNgWord, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiNgWordSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateNgWord(ngWordId, apiNgWord, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * NgWordApi - factory interface
 * @export
 */
export const NgWordApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NgWordApiFp(configuration)
    return {
        /**
         *
         * @summary Add a new NgWord
         * @param {ApiNgWordToAdd} apiNgWordToAdd NgWord object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNgWord(apiNgWordToAdd: ApiNgWordToAdd, options?: any): AxiosPromise<ApiNgWordSingle> {
            return localVarFp.addNgWord(apiNgWordToAdd, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deletes a ngWord
         * @param {number} ngWordId NgWord id to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNgWord(ngWordId: number, options?: any): AxiosPromise<ApiNgWordSingle> {
            return localVarFp.deleteNgWord(ngWordId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Returns ngWords inventories by status
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNgWords(sort?: string, order?: string, start?: number, end?: number, options?: any): AxiosPromise<ApiNgWords> {
            return localVarFp.getAllNgWords(sort, order, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single ngWord
         * @summary Find NgWord by ID
         * @param {number} ngWordId ID of ngWord to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNgWordById(ngWordId: number, options?: any): AxiosPromise<ApiNgWordSingle> {
            return localVarFp.getNgWordById(ngWordId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update an existing NgWord
         * @param {number} ngWordId ID of ngWord to return
         * @param {ApiNgWord} apiNgWord NgWord object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNgWord(ngWordId: number, apiNgWord: ApiNgWord, options?: any): AxiosPromise<ApiNgWordSingle> {
            return localVarFp.updateNgWord(ngWordId, apiNgWord, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NgWordApi - object-oriented interface
 * @export
 * @class NgWordApi
 * @extends {BaseAPI}
 */
export class NgWordApi extends BaseAPI {
    /**
     *
     * @summary Add a new NgWord
     * @param {ApiNgWordToAdd} apiNgWordToAdd NgWord object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NgWordApi
     */
    public addNgWord(apiNgWordToAdd: ApiNgWordToAdd, options?: any) {
        return NgWordApiFp(this.configuration).addNgWord(apiNgWordToAdd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deletes a ngWord
     * @param {number} ngWordId NgWord id to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NgWordApi
     */
    public deleteNgWord(ngWordId: number, options?: any) {
        return NgWordApiFp(this.configuration).deleteNgWord(ngWordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Returns ngWords inventories by status
     * @param {string} [sort] sorting column
     * @param {string} [order] ASC / DESC
     * @param {number} [start] Start position of retrieved data
     * @param {number} [end] End position of retrieved data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NgWordApi
     */
    public getAllNgWords(sort?: string, order?: string, start?: number, end?: number, options?: any) {
        return NgWordApiFp(this.configuration).getAllNgWords(sort, order, start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single ngWord
     * @summary Find NgWord by ID
     * @param {number} ngWordId ID of ngWord to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NgWordApi
     */
    public getNgWordById(ngWordId: number, options?: any) {
        return NgWordApiFp(this.configuration).getNgWordById(ngWordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update an existing NgWord
     * @param {number} ngWordId ID of ngWord to return
     * @param {ApiNgWord} apiNgWord NgWord object that needs to be added to the store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NgWordApi
     */
    public updateNgWord(ngWordId: number, apiNgWord: ApiNgWord, options?: any) {
        return NgWordApiFp(this.configuration).updateNgWord(ngWordId, apiNgWord, options).then((request) => request(this.axios, this.basePath));
    }
}
