/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
import {ApiGenres} from '../model';

/**
 * ProjectGenresApi - axios parameter creator
 * @export
 */
export const ProjectGenresApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a single or multiple genre
         * @summary Find projectGenre by ID
         * @param {number} projectId ID of project to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectGenreById: async (projectId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('getProjectGenreById', 'projectId', projectId)
            const localVarPath = `/projectGenres/{projectId}`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectGenresApi - functional programming interface
 * @export
 */
export const ProjectGenresApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectGenresApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a single or multiple genre
         * @summary Find projectGenre by ID
         * @param {number} projectId ID of project to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectGenreById(projectId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGenres>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectGenreById(projectId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProjectGenresApi - factory interface
 * @export
 */
export const ProjectGenresApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectGenresApiFp(configuration)
    return {
        /**
         * Returns a single or multiple genre
         * @summary Find projectGenre by ID
         * @param {number} projectId ID of project to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectGenreById(projectId: number, options?: any): AxiosPromise<ApiGenres> {
            return localVarFp.getProjectGenreById(projectId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectGenresApi - object-oriented interface
 * @export
 * @class ProjectGenresApi
 * @extends {BaseAPI}
 */
export class ProjectGenresApi extends BaseAPI {
    /**
     * Returns a single or multiple genre
     * @summary Find projectGenre by ID
     * @param {number} projectId ID of project to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGenresApi
     */
    public getProjectGenreById(projectId: number, options?: any) {
        return ProjectGenresApiFp(this.configuration).getProjectGenreById(projectId, options).then((request) => request(this.axios, this.basePath));
    }
}
