/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, {AxiosInstance, AxiosPromise} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    assertParamExists,
    createRequestFunction,
    DUMMY_BASE_URL,
    serializeDataIfNeeded,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    toPathString
} from '../common';
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
import {
    ApiProjectApplication,
    ApiProjectApplications,
    ApiProjectApplicationSingle,
    ApiProjectApplicationToAdd,
    ApiProjectApplicationToSearch
} from '../model';
import CONFIG from "../../const/DaoConfig";

/**
 * ProjectApplicationsApi - axios parameter creator
 * @export
 */
export const ProjectApplicationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Returns projectApplications
         * @param {ApiProjectApplicationToSearch} [filter]
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProjectApplications: async (filter?: ApiProjectApplicationToSearch, sort?: string, order?: string, start?: number, end?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/mypage/projectApplications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            let localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (filter !== undefined) {
                localVarQueryParameter['_filter'] = filter;
            }

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }

            if (start !== undefined) {
                localVarQueryParameter['_start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['_end'] = end;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter = CONFIG().CONFIG_HEADER().headers

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single projectApplication
         * @summary Find ProjectApplication by ID
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectApplicationById: async (projectApplicationId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectApplicationId' is not null or undefined
            assertParamExists('getProjectApplicationById', 'projectApplicationId', projectApplicationId)
            const localVarPath = `/mypage/projectApplications/{projectApplicationId}`
                .replace(`{${"projectApplicationId"}}`, encodeURIComponent(String(projectApplicationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'GET', ...baseOptions, ...options};
            let localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter = CONFIG().CONFIG_HEADER().headers

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing ProjectApplication
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {ApiProjectApplication} apiProjectApplication ProjectApplication object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectApplication: async (projectApplicationId: number, apiProjectApplication: ApiProjectApplication, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectApplicationId' is not null or undefined
            assertParamExists('updateProjectApplication', 'projectApplicationId', projectApplicationId)
            // verify required parameter 'apiProjectApplication' is not null or undefined
            assertParamExists('updateProjectApplication', 'apiProjectApplication', apiProjectApplication)
            const localVarPath = `/mypage/projectApplications/{projectApplicationId}`
                .replace(`{${"projectApplicationId"}}`, encodeURIComponent(String(projectApplicationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = {method: 'PUT', ...baseOptions, ...options};
            let localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter = CONFIG().CONFIG_HEADER().headers

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiProjectApplication, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectApplicationsApi - functional programming interface
 * @export
 */
export const ProjectApplicationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectApplicationsApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Returns projectApplications
         * @param {ApiProjectApplicationToSearch} [filter]
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllProjectApplications(filter?: ApiProjectApplicationToSearch, sort?: string, order?: string, start?: number, end?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiProjectApplications>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllProjectApplications(filter, sort, order, start, end, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a single projectApplication
         * @summary Find ProjectApplication by ID
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectApplicationById(projectApplicationId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiProjectApplicationSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectApplicationById(projectApplicationId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update an existing ProjectApplication
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {ApiProjectApplication} apiProjectApplication ProjectApplication object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectApplication(projectApplicationId: number, apiProjectApplication: ApiProjectApplication, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiProjectApplicationSingle>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectApplication(projectApplicationId, apiProjectApplication, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProjectApplicationsApi - factory interface
 * @export
 */
export const ProjectApplicationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectApplicationsApiFp(configuration)
    return {
        /**
         *
         * @summary Returns projectApplications
         * @param {ApiProjectApplicationToSearch} [filter]
         * @param {string} [sort] sorting column
         * @param {string} [order] ASC / DESC
         * @param {number} [start] Start position of retrieved data
         * @param {number} [end] End position of retrieved data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProjectApplications(filter?: ApiProjectApplicationToSearch, sort?: string, order?: string, start?: number, end?: number, options?: any): AxiosPromise<ApiProjectApplications> {
            return localVarFp.getAllProjectApplications(filter, sort, order, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single projectApplication
         * @summary Find ProjectApplication by ID
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectApplicationById(projectApplicationId: number, options?: any): AxiosPromise<ApiProjectApplicationSingle> {
            return localVarFp.getProjectApplicationById(projectApplicationId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update an existing ProjectApplication
         * @param {number} projectApplicationId ID of projectApplication to return
         * @param {ApiProjectApplication} apiProjectApplication ProjectApplication object that needs to be added to the store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectApplication(projectApplicationId: number, apiProjectApplication: ApiProjectApplication, options?: any): AxiosPromise<ApiProjectApplicationSingle> {
            return localVarFp.updateProjectApplication(projectApplicationId, apiProjectApplication, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectApplicationsApi - object-oriented interface
 * @export
 * @class ProjectApplicationsApi
 * @extends {BaseAPI}
 */
export class ProjectApplicationsApi extends BaseAPI {
    /**
     *
     * @summary Returns projectApplications
     * @param {ApiProjectApplicationToSearch} [filter]
     * @param {string} [sort] sorting column
     * @param {string} [order] ASC / DESC
     * @param {number} [start] Start position of retrieved data
     * @param {number} [end] End position of retrieved data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApplicationsApi
     */
    public getAllProjectApplications(filter?: ApiProjectApplicationToSearch, sort?: string, order?: string, start?: number, end?: number, options?: any) {
        return ProjectApplicationsApiFp(this.configuration).getAllProjectApplications(filter, sort, order, start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single projectApplication
     * @summary Find ProjectApplication by ID
     * @param {number} projectApplicationId ID of projectApplication to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApplicationsApi
     */
    public getProjectApplicationById(projectApplicationId: number, options?: any) {
        return ProjectApplicationsApiFp(this.configuration).getProjectApplicationById(projectApplicationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update an existing ProjectApplication
     * @param {number} projectApplicationId ID of projectApplication to return
     * @param {ApiProjectApplication} apiProjectApplication ProjectApplication object that needs to be added to the store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApplicationsApi
     */
    public updateProjectApplication(projectApplicationId: number, apiProjectApplication: ApiProjectApplication, options?: any) {
        return ProjectApplicationsApiFp(this.configuration).updateProjectApplication(projectApplicationId, apiProjectApplication, options).then((request) => request(this.axios, this.basePath));
    }
}
