/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ApiRefreshToken } from '../model';
// @ts-ignore
import { ApiToken } from '../model';
/**
 * RefreshTokenApi - axios parameter creator
 * @export
 */
export const RefreshTokenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Refresh Token
         * @param {ApiRefreshToken} apiRefreshToken Refresh token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshTokenPost: async (apiRefreshToken: ApiRefreshToken, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiRefreshToken' is not null or undefined
            assertParamExists('refreshTokenPost', 'apiRefreshToken', apiRefreshToken)
            const localVarPath = `/refreshToken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiRefreshToken, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RefreshTokenApi - functional programming interface
 * @export
 */
export const RefreshTokenApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RefreshTokenApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Refresh Token
         * @param {ApiRefreshToken} apiRefreshToken Refresh token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshTokenPost(apiRefreshToken: ApiRefreshToken, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshTokenPost(apiRefreshToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RefreshTokenApi - factory interface
 * @export
 */
export const RefreshTokenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RefreshTokenApiFp(configuration)
    return {
        /**
         * 
         * @summary Refresh Token
         * @param {ApiRefreshToken} apiRefreshToken Refresh token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshTokenPost(apiRefreshToken: ApiRefreshToken, options?: any): AxiosPromise<ApiToken> {
            return localVarFp.refreshTokenPost(apiRefreshToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RefreshTokenApi - object-oriented interface
 * @export
 * @class RefreshTokenApi
 * @extends {BaseAPI}
 */
export class RefreshTokenApi extends BaseAPI {
    /**
     * 
     * @summary Refresh Token
     * @param {ApiRefreshToken} apiRefreshToken Refresh token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefreshTokenApi
     */
    public refreshTokenPost(apiRefreshToken: ApiRefreshToken, options?: any) {
        return RefreshTokenApiFp(this.configuration).refreshTokenPost(apiRefreshToken, options).then((request) => request(this.axios, this.basePath));
    }
}
