/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiNotification } from './api-notification';

/**
 * 
 * @export
 * @interface ApiNotifications
 */
export interface ApiNotifications {
    /**
     * 
     * @type {number}
     * @memberof ApiNotifications
     */
    total?: number;
    /**
     * 
     * @type {Array<ApiNotification>}
     * @memberof ApiNotifications
     */
    data?: Array<ApiNotification>;
}


