/* tslint:disable */
/* eslint-disable */
/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiNotification
 */
export interface ApiNotification {
    /**
     * 
     * @type {number}
     * @memberof ApiNotification
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof ApiNotification
     */
    createdAt?: string;
    /**
     *
     * @type {number}
     * @memberof ApiNotification
     */
    userId: number;
    /**
     *
     * @type {string}
     * @memberof ApiNotification
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ApiNotification
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof ApiNotification
     */
    sendDate?: string;
}


