/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiUserDevice
 */
export interface ApiUserDevice {
    /**
     * 
     * @type {number}
     * @memberof ApiUserDevice
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserDevice
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDevice
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserDevice
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDevice
     */
    type: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserDevice
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDevice
     */
    badge: number;
}


