/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiBankTransferApplication } from './api-bank-transfer-application';

/**
 * 
 * @export
 * @interface ApiBankTransferApplications
 */
export interface ApiBankTransferApplications {
    /**
     * 
     * @type {number}
     * @memberof ApiBankTransferApplications
     */
    total?: number;
    /**
     * 
     * @type {Array<ApiBankTransferApplication>}
     * @memberof ApiBankTransferApplications
     */
    data?: Array<ApiBankTransferApplication>;
}


