/* tslint:disable */
/* eslint-disable */

/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ApiMypageThread
 */
export interface ApiMypageThread {
    /**
     *
     * @type {string}
     * @memberof ApiMypageThread
     */
    projectName: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageThread
     */
    senderName: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageThread
     */
    createdAt: string;
    /**
     *
     * @type {boolean}
     * @memberof ApiMypageThread
     */
    unreadFlag: boolean;
    /**
     *
     * @type {string}
     * @memberof ApiMypageThread
     */
    body: string;
    /**
     *
     * @type {number}
     * @memberof ApiMypageThread
     */
    projectApplicationId: number;
    /**
     *
     * @type {string}
     * @memberof ApiMypageThread
     */
    senderProfileImageUrl: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageThread
     */
    senderProfilePublicImageUrl: string;
}


