/* tslint:disable */
/* eslint-disable */

/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ApiUserProfileToAdd
 */
export interface ApiUserProfileToAdd {
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    address1: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    address2: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    postalCode1: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    postalCode2: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    tel: string;
    /**
     *
     * @type {Array<number>}
     * @memberof ApiUserProfileToAdd
     */
    genreIds: Array<number>;
    /**
     *
     * @type {number}
     * @memberof ApiUserProfileToAdd
     */
    areaId: number;
    /**
     *
     * @type {number}
     * @memberof ApiUserProfileToAdd
     */
    experienceYears: number;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    selfIntroduction: string;
    /**
     *
     * @type {string}
     * @memberof ApiUserProfileToAdd
     */
    password?: string;
}


