/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiUserDeviceToSearch
 */
export interface ApiUserDeviceToSearch {
    /**
     * 
     * @type {number}
     * @memberof ApiUserDeviceToSearch
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserDeviceToSearch
     */
    createdAtFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUserDeviceToSearch
     */
    createdAtTo?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDeviceToSearch
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDeviceToSearch
     */
    type?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserDeviceToSearch
     */
    token?: string;
}


