/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiMessageToAdd
 */
export interface ApiMessageToAdd {
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToAdd
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToAdd
     */
    senderId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToAdd
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToAdd
     */
    projectApplicationId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToAdd
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessageToAdd
     */
    body: string;
}


