/* tslint:disable */
/* eslint-disable */

/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ApiMypageBankAccount
 */
export interface ApiMypageBankAccount {
    /**
     *
     * @type {string}
     * @memberof ApiMypageBankAccount
     */
    gmoBankName: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageBankAccount
     */
    gmoBankBranchName: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageBankAccount
     */
    gmoBankAccountType: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageBankAccount
     */
    gmoBankAccountNumber: string;
    /**
     *
     * @type {string}
     * @memberof ApiMypageBankAccount
     */
    gmoBankAccountName: string;
}


