/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {ApiContractor} from './api-contractor';

/**
 *
 * @export
 * @interface ApiOrdererProject
 */
export interface ApiOrdererProject {
    /**
     *
     * @type {number}
     * @memberof ApiOrdererProject
     */
    projectId: number;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    recruitingStartDate: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    recruitingEndDate: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    projectName: string;
    /**
     *
     * @type {number}
     * @memberof ApiOrdererProject
     */
    remainingStock: number;
    /**
     *
     * @type {number}
     * @memberof ApiOrdererProject
     */
    status: number;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    orderImageUrl: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    orderPublicImageUrl: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    ordererName: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    workStartDate: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    restraintStartDate: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    restraintEndDate: string;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    areaName: string;
    /**
     *
     * @type {number}
     * @memberof ApiOrdererProject
     */
    minPrice?: number;
    /**
     *
     * @type {number}
     * @memberof ApiOrdererProject
     */
    maxPrice?: number;
    /**
     *
     * @type {string}
     * @memberof ApiOrdererProject
     */
    description: string;
    /**
     *
     * @type {number}
     * @memberof ApiOrdererProject
     */
    minimumExperienceYears?: number;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiOrdererProject
     */
    genreNames?: Array<string>;
    /**
     *
     * @type {Array<ApiContractor>}
     * @memberof ApiOrdererProject
     */
    contractors?: Array<ApiContractor>;
}


