/* tslint:disable */
/* eslint-disable */
/**
 * mtg_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiNgWords } from './api-ng-words';
import { ApiUsers } from './api-users';

/**
 * 
 * @export
 * @interface ApiMessage
 */
export interface ApiMessage {
    /**
     * 
     * @type {number}
     * @memberof ApiMessage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessage
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMessage
     */
    senderId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessage
     */
    senderName: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMessage
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessage
     */
    projectApplicationId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessage
     */
    projectName: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMessage
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessage
     */
    body: string;
    /**
     * 
     * @type {ApiNgWords}
     * @memberof ApiMessage
     */
    ngWords?: ApiNgWords;
    /**
     *
     * @type {ApiUsers}
     * @memberof ApiMessage
     */
    users?: ApiUsers;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiMessage
     */
    bodies?: Array<string>;
    /**
     *
     * @type {boolean}
     * @memberof ApiMessage
     */
    unreadFlag?: boolean;
}


