/* tslint:disable */
/* eslint-disable */
/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiMessageToSearch
 */
export interface ApiMessageToSearch {
    /**
     * 
     * @type {string}
     * @memberof ApiMessageToSearch
     */
    keyword?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToSearch
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessageToSearch
     */
    createdAtFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMessageToSearch
     */
    createdAtTo?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToSearch
     */
    senderId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToSearch
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToSearch
     */
    projectApplicationId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMessageToSearch
     */
    messageStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMessageToSearch
     */
    senderName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMessageToSearch
     */
    body?: string;
}


