/* tslint:disable */
/* eslint-disable */
/**
 * esint_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {ApiMypageThread} from './api-mypage-thread';

/**
 *
 * @export
 * @interface ApiMypageThreads
 */
export interface ApiMypageThreads {
    /**
     *
     * @type {number}
     * @memberof ApiMypageThreads
     */
    total?: number;
    /**
     *
     * @type {Array<ApiMypageThread>}
     * @memberof ApiMypageThreads
     */
    data?: Array<ApiMypageThread>;
}


